@baseUrl = http://localhost:3000

GET {{baseUrl}}/

### get all
GET {{baseUrl}}/api/users

### get by ID
GET {{baseUrl}}/api/User/

### get by name 
GET {{baseUrl}}/api/MarcusThorne

###
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "name": "test",
    "email": "testing3456@gmail.com",
    "age": 56
}

###
DELETE {{baseUrl}}/api/users/6a1c83c6c639a897950148f5